### ISSUE TITLE
Создание интеграции Auth-сервиса и AsyncApi

### ISSUE THREAD

**Issue by Karnet011** [v-v-d/Auth_sprint_1#33]
Создайте интеграцию Auth-сервиса и AsyncAPI-сервиса, используя контракт, который вы сгенерировали в прошлом задании.
При создании интеграции не забудьте учесть изящную деградацию Auth-сервиса. Как вы уже выяснили ранее, Auth сервис один из самых нагруженных, потому что в него ходят большинство сервисов сайта. И если он откажет, сайт отказать не должен. Обязательно учтите этот сценарий в интеграциях с Auth-сервисом.

**Comment by v-v-d** [comment]
Не требуется, т.к. на данный момент у auth нет информации, которая нужна async api через прямые запросы. Валидация токена происхоит в сервисе async api, а роли пользователя получаются из токена
